project:
  type: book
  output-dir: docs

book:
  title: "Mentor Canada     Data Science for Social Good (DSSG) Fellowship Project"
  reader-mode: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Week 1"
      chapters:
      - week1.qmd
    - part: "Week 2"
      chapters:
        - week2.qmd
        - dashboard.qmd   
    - part: "Week 3"
      chapters:
        - week3-ses-viz.qmd
    - part: "Week 4" 
      chapters: 
        - week4-ohe-clearning-xgb.qmd
    - references.qmd
  