project:
  type: book
  output-dir: docs

book:
  title: "Mentor Canada DSSG"
  reader-mode: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Week 1"
      chapters:
      - week1.qmd
    - part: "Week 2"
      chapters:
        - week2.qmd
        - dashboard.qmd    
    - references.qmd
  