name: dssg_env
channels:
  - defaults
  - conda-forge
dependencies:
  - conda
  - python=3.10
  - jupyter
  - nbformat
  - quarto
  - pandas
  - scikit-learn
  - matplotlib
  - siuba
  - plotly
  - pyarrow
